# Generated by Django 4.2.5 on 2023-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_cart_options_alter_cartorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercake',
            fields=[
                ('cakeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='cakeimg')),
                ('price', models.IntegerField(default=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='cartorder',
        ),
    ]
